#!/bin/bash

# 🚀 COMPLETE TESTING SCRIPT - Run this to test everything

echo "=========================================="
echo "🌱 STEP 1: Seed Database with Sample Data"
echo "=========================================="
echo ""
echo "Run this command:"
echo "  cd backend && node seeds.js"
echo ""
echo "Expected: 2 groups, 6 categories, 12 questions created ✅"
echo ""

echo "=========================================="
echo "🔧 STEP 2: Start Backend Server"
echo "=========================================="
echo ""
echo "Run this command:"
echo "  cd backend && npm start"
echo ""
echo "Expected: Server running on port 3000 (or your configured port) ✅"
echo ""

echo "=========================================="
echo "⚛️  STEP 3: Start Frontend Server (in NEW terminal)"
echo "=========================================="
echo ""
echo "Run these commands:"
echo "  cd frontend"
echo "  npm install  # if not done"
echo "  npm start"
echo ""
echo "Expected: React app on http://localhost:3000 ✅"
echo ""

echo "=========================================="
echo "👨‍🎓 STEP 4: Test as STUDENT"
echo "=========================================="
echo ""
echo "1. Go to http://localhost:3000"
echo "2. Click [S] Student"
echo "3. Enter any username (e.g., 'Ahmed')"
echo ""
echo "✅ You should see:"
echo "   - 2 Groups:"
echo "     📚 لغات البرمجة (6 Q)"
echo "     🌍 ثقافة عامة (6 Q)"
echo ""
echo "4. Click on 'لغات البرمجة'"
echo ""
echo "✅ You should see 3 categories:"
echo "   - JavaScript (2 Q)"
echo "   - Python (2 Q)"
echo "   - Java (2 Q)"
echo "   🎲 Random/Mixed (All categories)"
echo ""
echo "5. Select 'JavaScript' (or Random/Mixed)"
echo "6. Click [OK] Start Quiz"
echo ""
echo "✅ Quiz should start with JavaScript questions! 🎉"
echo ""

echo "=========================================="
echo "👨‍💼 STEP 5: Test Admin Panel - Groups"
echo "=========================================="
echo ""
echo "1. Go to http://localhost:3000"
echo "2. Click [A] Admin"
echo "3. Username: admin"
echo "4. Password: password123"
echo ""
echo "✅ Click [G] Groups tab"
echo "   You should see:"
echo "   - لغات البرمجة (with description)"
echo "   - ثقافة عامة (with description)"
echo "   - Question counts for each"
echo ""
echo "5. Click [E] Edit on one group"
echo "6. Modify name/description"
echo "7. Click [S] Save"
echo ""
echo "✅ Group should be updated! 🎉"
echo ""

echo "=========================================="
echo "❓ STEP 6: Test Admin Panel - Questions with Group"
echo "=========================================="
echo ""
echo "1. Go to Admin Panel"
echo "2. Click [Q] Questions tab"
echo "3. Click [+] Add New Question"
echo ""
echo "✅ You should see TWO new fields:"
echo "   - Category (required) - existing"
echo "   - Group (optional) - NEW! ⭐"
echo ""
echo "4. Fill the form:"
echo "   Category: JavaScript"
echo "   Group: لغات البرمجة"
echo "   Question: Test Question?"
echo "   Type: MCQ"
echo "   Answer 1: Option A (correct)"
echo "   Answer 2: Option B"
echo ""
echo "5. Click [+] Create"
echo ""
echo "✅ Question created with group! 🎉"
echo ""
echo "6. In questions list, verify your question shows:"
echo "   Type: MCQ | Category: 1 | Group: 1 ✅"
echo ""

echo "=========================================="
echo "✅ FINAL TEST: New Question in Student Quiz"
echo "=========================================="
echo ""
echo "1. Go back to Student mode"
echo "2. Select 'لغات البرمجة' group"
echo "3. Select 'JavaScript' category"
echo "4. Start quiz"
echo ""
echo "✅ Your new question should appear! 🎉"
echo ""

echo "=========================================="
echo "🎊 ALL TESTS COMPLETE!"
echo "=========================================="
echo ""
echo "✅ Database seeded with sample data"
echo "✅ Groups tab working in admin"
echo "✅ Question form has group selector"
echo "✅ Student sees groups and categories"
echo "✅ Student can start quiz by group"
echo "✅ Admin can manage groups"
echo "✅ Admin can link questions to groups"
echo ""
echo "🚀 System is READY!"
echo ""
